#!/bin/bash

# Settings
#Can be set via environment variables otherwise default

REDIS_SERVER="${REDIS_SERVER:-$(which redis-server)}"
REDIS_CLI="${REDIS_CLI:-$(which redis-cli)}"
CLUSTER_HOST="${CLUSTER_HOST:-127.0.0.1}"
PORT="${PORT:-6379}"
TIMEOUT="${TIMEOUT:-2000}"
NODES="${NODES:-6}"
REPLICAS="${REPLICAS:-1}"
ADDITIONAL_SETTINGS="${ADDITIONAL_SETTINGS:-""}"


# You may want to put the above config parameters into config.sh in order to
# override the defaults without modifying this script.

if [ -a config.sh ]
then
    source "config.sh"
fi

# Computed vars
ENDPORT=$((PORT+NODES))

if [ "$1" == "start" ]
then
    while [ $((PORT < ENDPORT)) != "0" ]; do
        echo "Starting $PORT"
	# Echo the command for starting the Redis server
        echo "$REDIS_SERVER --port $PORT --protected-mode yes --cluster-enabled yes --cluster-config-file nodes-${PORT}.conf --cluster-node-timeout $TIMEOUT --appendonly no --dbfilename dump-${PORT}.rdb --logfile ${PORT}.log --daemonize yes --bind ${CLUSTER_HOST} ${ADDITIONAL_SETTINGS}"
        $REDIS_SERVER --port $PORT --protected-mode yes --cluster-enabled yes --cluster-config-file nodes-${PORT}.conf --cluster-node-timeout $TIMEOUT --appendonly no --dbfilename dump-${PORT}.rdb --logfile ${PORT}.log --daemonize yes --bind ${CLUSTER_HOST} ${ADDITIONAL_SETTINGS}
        PORT=$((PORT+1))
    done
    exit 0
fi

if [ "$1" == "create" ]
then
    HOSTS=""
    while [ $((PORT < ENDPORT)) != "0" ]; do
        HOSTS="$HOSTS $CLUSTER_HOST:$PORT"
        PORT=$((PORT+1))
    done
    OPT_ARG="--cluster-yes"
    $REDIS_CLI --cluster create $HOSTS --cluster-replicas $REPLICAS $OPT_ARG
    exit 0
fi

if [ "$1" == "stop" ]
then
    while [ $((PORT < ENDPORT)) != "0" ]; do
        echo "Stopping $PORT"
        $REDIS_CLI -p $PORT shutdown nosave
        PORT=$((PORT+1))
    done
    exit 0
fi

if [ "$1" == "clean" ]
then
    echo "Cleaning *.log"
    rm -rf *.log
    echo "Cleaning appendonlydir-*"
    rm -rf appendonlydir-*
    echo "Cleaning dump-*.rdb"
    rm -rf dump-*.rdb
    echo "Cleaning nodes-*.conf"
    rm -rf nodes-*.conf
    exit 0
fi

echo "Usage: $0 [start|create|stop|clean]"
echo "start     -- Launch Redis Cluster instances."
echo "create    -- Create a cluster using redis-cli --cluster create."
echo "stop      -- Stop Redis Cluster instances."
echo "clean     -- Remove all instances data, logs, configs."
