name: test2
on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Install latest Redis
      run: |
        sudo tar xvzf ./redis-stable.tar.gz
        sudo mv ./redis-server /usr/local/bin/

    - name: Start Redis server
      run: |
        chmod +x ./redis-start.sh
        ./redis-start.sh

    - name: Configure and Build redis-adapter
      run: |
        cmake -S . -B build -DREDIS_ADAPTER_TEST=1
        cmake --build build

    - name: Run Tests
      run: |
        ./build/redis-adapter-test
