name: Build and Test redis-adapter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: alpine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apk --update add make cmake g++ redis

    - name: Redis Info
      run: |
        redis-cli info

    - name: Configure and Build redis-adapter
      run: |
        cmake -S . -B build -DREDIS_ADAPTER_TEST=1
        cmake --build build

    - name: Run Tests
      run: |
        ./build/redis-adapter-test
