name: Build and Test redis-adapter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Install latest Redis
      run: |
        curl -O http://download.redis.io/redis-stable.tar.gz
        tar xvzf redis-stable.tar.gz
        cd redis-stable
        make
        sudo make install

    - name: Start Redis server
      run: |
        chmod +x ./redis-start.sh
        ./redis-start.sh

    - name: Configure and Build redis-adapter
      run: |
        cmake -S . -B build -DREDIS_ADAPTER_TEST=1
        cmake --build build

    - name: Run Tests
      run: |
        ./build/redis-adapter-test
